/**
 * Interface chrome: labels, buttons, form errors, aria text, palette hints.
 * Editable portfolio copy (headings, bio, SEO descriptions, …) is NOT here:
 * it lives in the database and is managed in /admin.
 */
export const copy = {
  nav: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    experience: 'Experience',
    resume: 'Resume',
    contact: 'Contact',
    menu: 'Menu',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    primary: 'Primary',
    skipToContent: 'Skip to content',
    backToTop: 'Back to top',
    backToTopShort: 'Top',
  },
  /** Home sections. The headings are database copy (Page content → Home); these are only fallbacks. */
  home: {
    featured: { eyebrow: 'Selected Work', title: 'Projects worth a closer look', subtitle: null },
    toolkit: { eyebrow: 'Toolkit', title: 'What I build with', subtitle: null },
    cta: { eyebrow: 'Next', title: 'Want the full picture?', subtitle: null },
    viewAll: 'View all projects',
    readCaseStudy: 'Read the case study',
    pulseTitle: 'On GitHub',
    pulseRepos: 'Public repositories',
    pulseLastActivity: 'Last activity',
    pulseLink: 'See activity',
  },
  /** Skills ↔ projects links (About stack, home toolkit). */
  skills: {
    usedInOne: 'Used in 1 project',
    usedInMany: 'Used in {count} projects',
    projectsWith: 'Projects built with {name}',
  },
  hero: {
    focusLabel: 'Focus',
    stackLabel: 'Core Stack',
    basedLabel: 'Based In',
    ctaAbout: 'About Me',
    ctaProjects: 'View Projects',
    localTime: 'Local time',
  },
  projects: {
    featured: 'Featured',
    filters: 'Find a project',
    search: 'Search projects',
    searchPlaceholder: 'Name, description, or technology',
    technologies: 'Technologies',
    liveOnly: 'Live only',
    clearFilters: 'Clear filters',
    resultsAll: '{count} projects',
    resultsOne: '1 of {total} projects matches',
    resultsMany: '{count} of {total} projects match',
    noResults: 'No projects match these filters.',
    noResultsLead: 'Try another search or technology, or clear the filters.',
    live: 'Live',
    liveDemo: 'Live Demo',
    source: 'Source',
    details: 'Project Details',
    project: 'Project',
    status: 'Status',
    repositories: 'Repositories',
    overview: 'Overview',
    gallery: 'Gallery',
    writeup: 'Project write-up',
    previousProject: 'Previous project',
    nextProject: 'Next project',
    allRepos: 'All repositories',
    backToProjects: 'All projects',
    builtWith: 'Built with',
    links: 'Links',
    empty: 'Projects are on their way.',
    onThisPage: 'On this page',
    caseStudy: 'Case study',
    timeline: 'Development timeline',
    timelineLead: 'How the project came together, milestone by milestone.',
    related: 'Related projects',
    challenge: 'Challenge',
    solution: 'Solution',
    hidden: 'Hidden',
    watchVideo: 'Watch the video',
    videoTitle: '{title}: video',
    viewImage: 'View image {n} of {count}',
    closeImage: 'Close image',
    previousImage: 'Previous image',
    nextImage: 'Next image',
    milestoneLink: 'Learn more',
    milestoneKinds: {
      started: 'Started',
      feature: 'Feature',
      release: 'Release',
      launch: 'Launch',
      refactor: 'Rework',
      other: 'Milestone',
    },
  },
  github: {
    follow: 'Follow',
    less: 'Less',
    more: 'More',
    contributions: 'Contributions',
    repositories: 'Selected Repositories',
    statRepos: 'Public Repos',
    statStars: 'Stars Earned',
    statForks: 'Total Forks',
    statFollowers: 'Followers',
    contributionsCaption: '{count} contributions in the last 6 months',
    contributionsCaptionOne: '1 contribution in the last 6 months',
    calendarLabel: 'GitHub contribution calendar: {count} contributions in the last 26 weeks',
    recentActivity: 'Recent Activity',
    lastActivity: 'Last public activity',
    updated: 'Updated',
    calendarUnavailable: 'Contribution data unavailable',
    unavailable: "GitHub data isn't available right now.",
    loading: 'Loading live activity…',
    cellOne: '1 contribution on {date}',
    cellMany: '{count} contributions on {date}',
    cellNone: 'No contributions on {date}',
    events: {
      push: 'Pushed to {ref}',
      pushNoRef: 'Pushed commits',
      commit: 'Committed “{message}” to',
      createBranch: 'Created branch {ref}',
      createTag: 'Created tag {ref}',
      createRepository: 'Created repository',
      release: 'Published release {tag}',
      releaseNoTag: 'Published a release',
      pullRequestOpened: 'Opened pull request: {title}',
      pullRequestClosed: 'Closed pull request: {title}',
      pullRequestMerged: 'Merged pull request: {title}',
      pullRequestReopened: 'Reopened pull request: {title}',
      issueOpened: 'Opened issue: {title}',
      issueClosed: 'Closed issue: {title}',
      issueReopened: 'Reopened issue: {title}',
    },
  },
  projectGithub: {
    heading: 'Development activity',
    lead: 'Live data from the project’s public GitHub repositories, kept apart from the curated timeline.',
    loading: 'Loading GitHub activity…',
    unavailable: "GitHub data isn't available right now.",
    unavailableOne: '1 linked repository is unavailable and isn’t included.',
    unavailableMany: '{count} linked repositories are unavailable and aren’t included.',
    coverage: 'Based on {covered} of {of} repositories.',
    statRepositories: 'Repositories',
    statStars: 'Stars',
    statForks: 'Forks',
    statCommits: 'Commits',
    statCommitsNote: 'Default branch · past year',
    statContributors: 'Contributors',
    statReleases: 'Releases',
    lastActivity: 'Last activity',
    activityTitle: 'Commit activity',
    activityCaption: 'Commits to each repository’s default branch per week, {from} – {to}, as computed by GitHub. A time-bounded count, not a lifetime total.',
    activityLabel: 'Weekly commits from {from} to {to}: {count} in total',
    activityBarOne: '1 commit · week of {date}',
    activityBarMany: '{count} commits · week of {date}',
    activityEmpty: 'No commits to the default branch in the past year.',
    activityUnavailable: 'Commit activity is unavailable right now.',
    activityPendingOne: 'GitHub is still computing statistics for 1 repository; it will be included shortly.',
    activityPendingMany: 'GitHub is still computing statistics for {count} repositories; they will be included shortly.',
    tableMonth: 'Month',
    tableCommits: 'Commits',
    languagesTitle: 'Languages',
    languagesCaption: 'Share of code by bytes, as GitHub detects it, across the repositories.',
    languageOther: 'Other',
    repositoriesTitle: 'Repositories',
    primary: 'Primary',
    archived: 'Archived',
    periodCommits: '{count} commits in the past year',
    periodCommitsOne: '1 commit in the past year',
    commitsTitle: 'Recent commits',
    releasesTitle: 'Recent releases',
    releasesNone: 'No published releases yet.',
    prerelease: 'Pre-release',
    contributorsTitle: 'Contributors',
    contributorsCaption: 'GitHub accounts with commits on the default branches; bots excluded.',
    contributorsMore: '+{count} more',
    labels: {
      frontend: 'Frontend',
      backend: 'Backend',
      api: 'API',
      infrastructure: 'Infrastructure',
      mobile: 'Mobile',
      library: 'Library',
      docs: 'Documentation',
      other: 'Other',
    },
  },
  experience: {
    career: 'Career',
    education: 'Education',
    current: 'Current',
    present: 'Present',
    expected: 'Expected',
  },
  resume: {
    download: 'Download Resume',
    openFull: 'Open Full Page',
    viewerTitle: 'Resume PDF',
    viewerError: "The preview couldn't load. You can still open or download the PDF.",
    unavailableTitle: 'The resume is being updated',
    unavailableBody: 'A new version will be here shortly. In the meantime, the contact page is the quickest way to reach me.',
  },
  contact: {
    emailLabel: 'Email',
    name: 'Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'you@example.com',
    subjectPlaceholder: "What's this about?",
    messagePlaceholder: "Tell me a little about what you're reaching out about…",
    errors: {
      nameRequired: 'Please add your name',
      emailRequired: 'Please add an email',
      emailInvalid: 'That email looks off',
      subjectRequired: 'Add a short subject',
      subjectInvalid: 'The subject must be a single line',
      messageRequired: 'A short note helps',
      tooLong: 'That is a bit too long',
      send: 'Something went wrong. Please try again.',
      unavailable: 'The contact form is temporarily unavailable. Please email me directly.',
    },
    send: 'Send Message',
    sending: 'Sending…',
    sentTitle: 'Message sent',
    sentBody: "Thanks, {name}! Your message is in my inbox. I'll get back to you as soon as I can.",
    sendAnother: 'Send another',
    directNote: 'This form goes straight to my inbox. You can also email me directly at',
  },
  footer: {
    site: 'Site',
    connect: 'Connect',
    email: 'Email',
    resume: 'Resume',
    lastUpdated: 'Last updated',
    preferences: 'Preferences',
    admin: 'Admin',
  },
  toggles: {
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
  },
  palette: {
    open: 'Search commands',
    title: 'Command palette',
    placeholder: 'Jump to a page or run a command…',
    close: 'Close',
    empty: 'No commands found',
    emptyHint: 'Try a page name, "resume", or "email".',
    result: 'result',
    results: 'results',
    groups: { nav: 'Navigation', actions: 'Actions', profiles: 'Profiles' },
    hints: { navigate: 'Navigate', select: 'Select', close: 'Close' },
    downloadResume: 'Download resume',
    copyEmail: 'Copy email address',
    copied: 'Email address copied',
    copyFailed: 'Copy failed — the address is',
    themeLight: 'Switch to light theme',
    themeDark: 'Switch to dark theme',
    openProfile: 'Open {platform} profile',
    keywords: {
      home: ['home', 'start', 'landing', 'intro', 'top'],
      about: ['about', 'bio', 'background', 'me', 'snapshot', 'stack', 'skills', 'tools', 'interests'],
      projects: ['projects', 'work', 'portfolio', 'repos', 'code', 'builds', 'github'],
      experience: ['experience', 'work', 'career', 'jobs', 'employment', 'education', 'degree', 'school'],
      resume: ['resume', 'cv', 'curriculum', 'pdf'],
      contact: ['contact', 'email', 'hire', 'message', 'reach out', 'talk'],
      downloadResume: ['resume', 'cv', 'pdf', 'download', 'save'],
      copyEmail: ['email', 'copy', 'address', 'mail', 'contact'],
      theme: ['theme', 'dark', 'light', 'mode', 'appearance', 'colour', 'color'],
      profiles: ['profile', 'social', 'network', 'code', 'source'],
    },
  },
  notFound: {
    code: '404',
    heading: 'Page Not Found',
    lead: "That route doesn't exist on this site. It may have been renamed, or the link that brought you here is out of date.",
    home: 'Back to Home',
    projects: 'View Projects',
    title: '404 — Page Not Found',
    description: "This page doesn't exist. Head back to the homepage to keep browsing.",
  },
  error: {
    title: 'Something went wrong',
    lead: 'An unexpected error occurred while loading this page.',
    retry: 'Try again',
  },
  pager: { previous: 'Previous', next: 'Next' },
  loading: { label: 'Loading' },
};

export type Copy = typeof copy;

/** Fills `{name}` placeholders in a copy template. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}
